name: panvimdoc

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: codestats
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: auto-generate vimdoc'
          branch: ${{ github.head_ref }}
